# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S-jocWlKe_WHorXauzaxpbZbEYEE5uBA
"""

print("Hello World")

a=5
b=2
c=a+b
print(c)

a=7.5
h=7.5
S=a*h/2
print(S)

a=4
b=5
c=3
x=(a**2+b**2-c**3)/2
print(x)

a=8
b=6
x=(a+b)**2
print(x)

a=15
b=10
c=5
x=(a+b)/c
print(x)

a=3
b=5
x=(a+b)**2
print(x)

a=5
b=int(input())
print(b+a)

a=15
b=10
c=int(input())
print((a+b)/c)

a=4
b=6
print (((a**3+14)/5)*b)

a=int(input())
print(a**2)
n=int(input())
print(a**2/n)

a=3600
print(a/60)
print(a/3600)

n=int(input())
print(n+n*n+n*n*n)

a=3
b=4
c=5
h=4
print(a+b+c)
print((a*h)/2)

a=int(input())
b=int(input())
print((a+b)**2)