# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NPRujGfMECF0YPQXYeGso76M9-L7UC2Y
"""

language = "english"
if language == "english":
  print("Hello")
  print("End")

language = "russuan"
if language == "english":
  print("Hello")
else:
  print("Привет")
  print("End")

language = "russian"
if language == "english":
  print("Hello")
  print("World")
else:
  print("Привет")
  print("мир")

language = "german"
if language == "english":
  print("Hello")
  print("World")
elif language == "german":
  print("Hallo")
  print("Welt")
else:
 print("Привет")
 print("мир")

language = "russian"
daytime = "morning"
if language == "english":
  if daytime == "morning":
     print("Good morning")
else:
     print("Good evening")
else:
if daytime == "morning":
      print("Доброе утро")
else:
    print("Добрый вечер")

n = 6
if n / 2 == 0:
 print('Чётное число')
else:
  print('Нечётное число')

n= int(input())
if n>40:
  print("stonks")
if n<40:
  print("not stonks")

n= int(input())
if n == 1:
  print("January")
if n == 2:
  print("February")
if n == 3:
  print("March")
if n == 4:
  print("April")
if n == 5:
  print("May")
if n == 6:
  print("June")
if n == 7:
  print("July")
if n == 8:
  print("August")
if n == 9:
 print("September")
if n == 10:
  print("October")
if n == 11:
  print("November")
if n == 12:
  print("December")